apiVersion: v1
kind: LimitRange
metadata:
  name: memory-limit-range
  namespace: dev-namespace
spec:
  limits:
  - default:
      memory: 500Mi
      cpu: 1
    defaultRequest:
      memory: 500Mi
      cpu: 1
    type: Container
