apiVersion: v1
kind: Pod
metadata:
  name: tomcat-nginix
  namespace: dev-namespace
  labels:
    app: tomcat
spec:
  containers:
  - name: mytomcat
    image: mskoushik007/tomcat:1.0.1
  - name: nginx
    image: nginx:1.14.2
